---
name: Deploy Bicep

on:
  workflow_call:
    inputs:
      BICEP_FILE:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
      LOCATION:
        required: true
        type: string
      BICEP_PARAMETERS_FILE:
        required: false
        type: string
        default: ""
      SCOPE:
        description: 'Scope of the action (Allowed values: tenant, managementgroup, subscription, resourcegroup)'
        required: true
        type: string
        default: 'subscription'
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_RESOURCE_GROUP:
        required: false
      BICEP_PARAMETERS_TOKENS:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  bicep-deploy:
    name: Bicep Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Tokenize Bicep Parameters
        if: ${{ inputs.BICEP_PARAMETERS_FILE != '' }}
        uses: cschleiden/replace-tokens@v1.3
        env:
          ${{ fromJson(secrets.BICEP_PARAMETERS_TOKENS || '{}') }}
        with:
          files: ${{ inputs.BICEP_PARAMETERS_FILE }}

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Azure CLI for Bicep
        shell: bash
        run: |
          az config set bicep.use_binary_from_path=false

      - name: Bicep Deployment (Subscription)
        if: ${{ inputs.SCOPE == 'subscription' }}
        shell: bash
        run: |
          az deployment sub create \
            --name deploy-${{ github.run_id }} \
            --template-file ${{ inputs.BICEP_FILE }} \
            --location ${{ inputs.LOCATION }} \
            --parameters ${{ inputs.BICEP_PARAMETERS_FILE }}

      - name: Bicep Deployment (Resource Group)
        if: ${{ inputs.SCOPE == 'resourcegroup' }}
        shell: bash
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name deploy-${{ github.run_id }} \
            --template-file ${{ inputs.BICEP_FILE }} \
            --parameters ${{ inputs.BICEP_PARAMETERS_FILE }}
