---
name: Lint YAML

on:
  workflow_call:
    inputs:
      RUNS_ON:
        description: 'OS to run the job on. Default is ubuntu-latest.'
        required: false
        default: 'ubuntu-24.04'
        type: string

      PYTHON_VERSION:
        description: 'Python version to use. Default is 3.13.'
        required: false
        default: '3.13'
        type: string

      YAMLLINT_CONFIG_PATH:
        description: 'Path to yamllint config file. Default is .yamllint.'
        required: false
        default: '.yamllint'
        type: string

      LINT_PATH:
        description: 'Path to lint directory. Default is .'
        required: false
        default: '.'
        type: string

jobs:
  lint:
    name: Lint YAML
    runs-on: ${{ inputs.RUNS_ON }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Install yamllint
      run: |
        python \
          -m pip \
          install \
          --upgrade pip

        pip install \
          yamllint

    - name: Run yamllint
      run: |
        yamllint \
          --config-file ${{ inputs.YAMLLINT_CONFIG_PATH }} \
          ${{ inputs.LINT_PATH }}
